---
- hosts: 192.168.4.101
  vars:
       tmpdir: "/tmp"
       redis_zip_url: "http://download.redis.io/releases/redis-4.0.2.tar.gz"
       zip_dest_dir: "/var/redis"
       zip_file: "redis-4.0.2.tar.gz"

  become: true

  tasks:
  #- name: download redis software
    #get_url:
      #url: http://download.redis.io/releases/redis-4.0.2.tar.gz
      #dest: /var/redis/redis-4.0.2.tar.gz

  - name: download redis software
    get_url:
      url: "{{ redis_zip_url }}"
      dest: "{{ zip_dest_dir }}"
      force: no

  - name: unarchive
    shell: tar xzf {{ zip_dest_dir }}/{{ zip_file }}
    args:
      #chdir: /var/redis
      chdir: "{{ zip_dest_dir }}"
